### ISSUE TITLE
Tab panel issue.

### ISSUE THREAD

**Issue by ThePlaytime** [SydneyMOD/SydneyHUD#22]
I can't tell if it's due to resolution scaling or something else.
But all the stats for kills and accuracy on the right side panel are inside my white mask, written in white text, it can't be read at all.

I assume this is resolution scaling? Since the mask is excessively pixelated and warped at 5760*1080.
A possible font color change?

**Comment by katabame** [comment]
Hi ThePlayTime,
Can I see the screenshot of this issue? (file can attach in comment)
And "Tab panel font size" option is in mod option menu(sorry, I can' remember where menu this having)
Could you change font size via this option to solve your issue? I hope this will help you.
If not, pleade tell me. I'll find the cause.

**Comment by ThePlaytime** [comment]
![20170502132011_1](https://cloud.githubusercontent.com/assets/28307433/25630195/48f0b9f6-2f3a-11e7-9634-0ebd771a4bb4.jpg)

Depending on the mask (or is it by character? I never paid much attention) it can completely block out the statistics due to the white on white coloring. It's not AS bad in this screenshot, but I've seen some that had it much worse and you could barely read anything.

**Comment by katabame** [comment]
I saw your attacked screenshot, it helped me.
In my develop environment, the mask image appearing top of right tab panel. (texts are shown below the mask)
I'm sure this isn't caused by SydneyHUD. but I don't know its (vanilla)PAYDAY2 feature or caused by another mod.

Could you try change game resolution? (I'm using 1280x720)
If it solved this, the issue caused by PAYDAY2.

**Comment by katabame** [comment]
Mark this as solved cause not respond in 7days.
If respond, open again.
